server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: bookreservation
          destination: bookrental
          contentType: application/json
        output:
          destination: bookrental
          contentType: application/json
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
        input:
          group: bookreservation
          destination: bookrental
          contentType: application/json
        output:
          destination: bookrental
          contentType: application/json