apiVersion: v1
kind: Service
metadata:
  name: reservation-svc
  labels:
    app: reservation
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: ccteam4acr.azurecr.io/reservation
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /reservations
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /reservations
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: EMBED_TOMCAT_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: spring-dev
                  key: JAVA_OPTS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-dev
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_PASS